# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy Node.js app to Azure Web App - fitw

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master

      - name: Set up Node.js version
        uses: actions/setup-node@v1
        with:
          node-version: "14.x"

      - name: yarn install, build, and test
        run: |
          yarn install
          yarn build
          yarn test

      - name: "Deploy to Azure Web App"
        uses: azure/webapps-deploy@v2
        with:
          app-name: "fitw"
          slot-name: "production"
          publish-profile: ${{ secrets.AzureAppService_PublishProfile_057c435ef5d1408bb1c566377cd23d47 }}
          package: .
